from.C_M import CM
C=CM()
class ArgumentParser:
	def parse_arguments(U):
		S='-rm';R='Random_Info';Q='Remove_Ads';P='AES_Logs';O='Merge';N='input';I='-C';B='store_true'
		class T(C.argparse.ArgumentParser):
			def error(E,message):
				D=message;B=''
				for A in E._actions:
					if A.option_strings and any(A in D for A in A.option_strings):
						if A.dest==N:B=f'''\n{C.lb}[ {C.y}FYI ! {C.lb}] {C.g}Make Sure There Is "No Extra Space" In The Folder/Apk Name In The Input Text. If Yes, Then Remove Extra Space & Correct It By Renaming It.\n\n\n{C.lb}[ {C.pr}* {C.lb}] {C.c}With Your Certificate ( Input Your pem/crt/cert Path )\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -i YourApkPath.apk {C.rkj}-c {C.y}certificate.cert\n\n\n{C.lb}[ {C.pr}* {C.lb}] {C.c}If Apk is Flutter Then Use Additional Flag {C.rkj}-f\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -i YourApkPath.apk -c certificate.cert {C.rkj}-f\n\n\n{C.lb}[ {C.pr}* {C.lb}] {C.c}Pairip CERT SSL Bypass ( Without Sign Apk Use Only in VM/Multi_App ){C.c}\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -i YourApkPath.apk -c certificate.cert {C.rkj}-p\n\n\n{C.lb}[ {C.pr}* {C.lb}] {C.c}Hook Android ID For One Device Login Bypass Use {C.rkj}-D {C.c}Flag (Input Your Original 16 Digit Android ID)\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -i YourApkPath.apk {C.rkj}-D {C.y}7e9f51f096bd5c83\n\n\n{C.lb}[ {C.pr}* {C.lb}] {C.c}If you are using an Emulator in PC Then Use Additional Flag {C.rkj}-e\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -i YourApkPath.apk -c certificate.cert {C.rkj}-e\n\n\n{C.lb}[ {C.pr}* {C.lb}] {C.c}If Failed SigCopy Use Another Method ( default apksigcopier ) {C.rkj}-p {C.rkj}-s2\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -i YourApkPath.apk -c certificate.cert {C.rkj}-p {C.rkj}-s2\n'''
						elif A.dest==O:B=f"""\n{C.lb}[ {C.y}INFO {C.lb}] {C.c}Only Merge Apk\n\n\n{C.lb}[ {C.y}INFO {C.lb}] {C.c}Merge Extension {C.y}( .apks/.xapk/.apkm )\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher {C.rkj}-m {C.g}Your_Apk_Path.apks\n"""
						elif A.dest==P:B=f"""\n{C.lb}[ {C.y}INFO {C.lb}] {C.c}AES MT Logs Inject\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -L Your_Apk_Path.apk\n\n\n{C.lb}[ {C.y}INFO {C.lb}] {C.c}Do U Want Separate AES.smali Dex Use Flags {C.rkj}-s\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -L Your_Apk_Path.apk {C.rkj}-s\n"""
						elif A.dest==Q:B=f"""\n{C.lb}[ {C.y}INFO {C.lb}] {C.c}Ads Remove/Patching\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -rm Your_Apk_Path.apk\n"""
						elif A.dest==R:B=f"""\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -r Your_Apk_Path.apk\n\n\n{C.lb}[ {C.y}INFO {C.lb}] {C.c}Hook Android ID For One Device Login Bypass Use {C.rkj}-D {C.c}Flag (Input Your Original 16 Digit Android ID)\n\n\n{C.lb}[ {C.y}Ex. {C.lb}] {C.g}ApkPatcher -r Your_Apk_Path.apk {C.rkj}-D {C.y}7e9f51f096bd5c83\n"""
						break
				exit(f"\n{C.lb}[ {C.rd}Error ! {C.lb}] {C.rd} {D}\n\n{B}")
		H=T(description=f"{C.c}ApkPatcher Script")if any(A.startswith('-')for A in C.sys.argv[1:])else C.argparse.ArgumentParser(description=f"{C.c}ApkPatcher Script");E=H.add_mutually_exclusive_group(required=True);E.add_argument('-i',dest=N,help=f"{C.y}➸{C.g} Input APK Path...{C.c}");E.add_argument('-m',dest=O,help=f"{C.y}➸{C.g} Anti-Split ( Only Merge Apk ){C.c}");E.add_argument('-L',dest=P,help=f"{C.y}➸{C.g} AES MT Logs Inject{C.c}");E.add_argument(S,dest=Q,help=f"{C.y}➸{C.g} Ads Remove/Patching{C.c}");E.add_argument('-r',dest=R,help=f"{C.y}➸{C.g} Random/Fake Device Info{C.c}");E.add_argument(I,dest='Credits_Instruction',action=B,help=f"{C.y}➸{C.g} Show Instructions & Credits{C.c}");A=H.add_argument_group(f"{C.rkj}[ * ] Additional Flags{C.c}");A.add_argument('-a','--APKEditor',action=B,help=f"{C.y}➸ {C.g}APKEditor ( Default APKTool ){C.c}");A.add_argument('-c',dest='CA_Certificate',type=str,nargs='*',help=f"{C.y}➸{C.g} Input Your HttpCanary/Reqable/ProxyPin etc. Capture Apk's CA-Certificate{C.c}");A.add_argument('-D',dest='Android_ID',type=str,help=f"{C.y}➸{C.g} Custom Android ID ( Input Your Android ID ){C.c}");A.add_argument('-f',dest='Flutter',action=B,help=f"{C.y}➸{C.g} Flutter SSL Bypass ( With Smali Patch ){C.c}");A.add_argument('-p',dest='Pairip',action=B,help=f"{C.y}➸{C.g} Pairip CERT SSL Bypass ( Without Sign Apk Use Only in VM/Multi_App ){C.c}");A.add_argument('-P',dest='Purchase',action=B,help=f"{C.y}➸{C.g} Purchase/Paid/Price{C.c}");A.add_argument('-S',dest='AES_MS',action=B,help=f"{C.y}➸{C.g} Do U Want Separate AES.smali Dex{C.c}");A.add_argument('-e',dest='For_Emulator',action=B,help=f'{C.y}➸{C.g} If you are using an emulator in PC then use it the "-e" additional flag{C.c}');A.add_argument('-s2',dest='SigCopy2',action=B,help=f"{C.y}➸{C.g} If Failed SigCopy Use Another Method ( default apksigcopier ){C.c}");A.add_argument('-skip',dest='Skip_Patch',nargs='*',help=f"{C.y}➸{C.g} Skip Patch (e.g., getAcceptedIssuers){C.r}");J=C.sys.argv[1:];K='.apk','.apks','.apkm','.xapk';D=[];F=None;L=False
		for(M,G)in enumerate(J):
			if G in['-i','-m','-L',S,'-r',I]:F,D=M+1,D+[G]
			elif F and(G.endswith(K)or C.os.path.isdir(G)):D,F=D+[' '.join(J[F:M+1])],None;L=True
			elif not F:D.append(G)
		if not L and C.sys.argv[1:2]!=[I]:print(f"\n{C.lb}[ {C.pr}* {C.lb}] {C.c} Only Supported Extensions {C.g}{K}\n")
		print(f"\n{C.lb}[ {C.pr}* {C.lb}] {C.c} Input Path {C.g}➸❥{C.y}",*D,f"{C.r}\n");return H.parse_args(D)